// <auto-generated />
using System;
using CarProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719163740_AddMissingFieldsAndGioHang")]
    partial class AddMissingFieldsAndGioHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarProject.Models.ChiNhanhShowroom", b =>
                {
                    b.Property<string>("MaChiNhanh")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDayNong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuanLy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThanhPho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiNhanh");

                    b.HasIndex("MaQuanLy");

                    b.ToTable("ChiNhanhShowroom", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.ChiTietKhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("ChiTietKhachHang", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.ChuongTrinhKhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MucGiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("ChuongTrinhKhuyenMai", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.DonDatCoc", b =>
                {
                    b.Property<int>("MaDonCoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonCoc"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaPhienBan")
                        .HasColumnType("int");

                    b.Property<string>("MaQuanLyDuyet")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayHenNhanXe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoDon")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SepayTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonCoc");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaPhienBan");

                    b.HasIndex("MaQuanLyDuyet");

                    b.ToTable("DonDatCoc", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.DongXe", b =>
                {
                    b.Property<int>("MaDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDong"));

                    b.Property<string>("KieuDang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHang")
                        .HasColumnType("int");

                    b.Property<string>("TenDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDong");

                    b.HasIndex("MaHang");

                    b.ToTable("DongXe", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaPhienBan")
                        .HasColumnType("int");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaPhienBan");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.HangXe", b =>
                {
                    b.Property<int>("MaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHang"));

                    b.Property<string>("DuongDanLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHang");

                    b.ToTable("HangXe", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.HoaDonMuaXe", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("GiaXeThucTe")
                        .HasColumnType("bigint");

                    b.Property<int>("MaDonCoc")
                        .HasColumnType("int");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhienBan")
                        .HasColumnType("int");

                    b.Property<string>("MaQuanLyXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayXuatHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoKhung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoTienDaThanhToan")
                        .HasColumnType("bigint");

                    b.Property<long>("SoTienDuocGiam")
                        .HasColumnType("bigint");

                    b.Property<long>("ThueTruocBaVaPhiLanBanh")
                        .HasColumnType("bigint");

                    b.Property<long>("TongTienPhaiTra")
                        .HasColumnType("bigint");

                    b.Property<string>("TrangThaiHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDonCoc");

                    b.ToTable("HoaDonMuaXe", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.KenhTuVan", b =>
                {
                    b.Property<int>("MaKenh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKenh"));

                    b.Property<string>("UrlMessenger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSMS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlZalo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKenh");

                    b.ToTable("KenhTuVan", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.LichHenLaiThu", b =>
                {
                    b.Property<int>("MaLichHen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHen"));

                    b.Property<string>("GioHen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiLai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaDong")
                        .HasColumnType("int");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoBangLaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YKienKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichHen");

                    b.HasIndex("MaChiNhanh");

                    b.HasIndex("MaDong");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("LichHenLaiThu", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrinhDuyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.PhienBanXe", b =>
                {
                    b.Property<int>("MaPhienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhienBan"));

                    b.Property<string>("DongCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GiaNiemYet")
                        .HasColumnType("bigint");

                    b.Property<string>("HopSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNhietLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDong")
                        .HasColumnType("int");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTrongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenPhienBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhienBan");

                    b.HasIndex("MaDong");

                    b.ToTable("PhienBanXe_SanPham", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.QuangCaoBanner", b =>
                {
                    b.Property<int>("MaBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanner"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDanLienKet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuanLyCapNhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTuHienThi")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiKichHoat")
                        .HasColumnType("bit");

                    b.HasKey("MaBanner");

                    b.HasIndex("MaQuanLyCapNhat");

                    b.ToTable("QuangCaoBanner", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaXacNhanEmail")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("MaXacNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.ThongKeTongHop_Boss", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<string>("KyBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaDongXeBanChayNhat")
                        .HasColumnType("int");

                    b.Property<int>("SoDonCocBiHuy")
                        .HasColumnType("int");

                    b.Property<long>("TongDoanhThu")
                        .HasColumnType("bigint");

                    b.Property<int>("TongLuotLaiThu")
                        .HasColumnType("int");

                    b.Property<int>("TongLuotXemWeb")
                        .HasColumnType("int");

                    b.Property<int>("TongSoXeDaBan")
                        .HasColumnType("int");

                    b.Property<long>("TongTienCocThuVe")
                        .HasColumnType("bigint");

                    b.HasKey("MaThongKe");

                    b.HasIndex("MaChiNhanh");

                    b.HasIndex("MaDongXeBanChayNhat");

                    b.ToTable("ThongKeTongHop_Boss", (string)null);
                });

            modelBuilder.Entity("CarProject.Models.ChiNhanhShowroom", b =>
                {
                    b.HasOne("CarProject.Models.TaiKhoan", "QuanLy")
                        .WithMany()
                        .HasForeignKey("MaQuanLy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("CarProject.Models.DonDatCoc", b =>
                {
                    b.HasOne("CarProject.Models.TaiKhoan", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarProject.Models.PhienBanXe", "PhienBan")
                        .WithMany()
                        .HasForeignKey("MaPhienBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarProject.Models.TaiKhoan", "QuanLyDuyet")
                        .WithMany()
                        .HasForeignKey("MaQuanLyDuyet")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("KhachHang");

                    b.Navigation("PhienBan");

                    b.Navigation("QuanLyDuyet");
                });

            modelBuilder.Entity("CarProject.Models.DongXe", b =>
                {
                    b.HasOne("CarProject.Models.HangXe", "HangXe")
                        .WithMany()
                        .HasForeignKey("MaHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangXe");
                });

            modelBuilder.Entity("CarProject.Models.GioHang", b =>
                {
                    b.HasOne("CarProject.Models.PhienBanXe", "PhienBan")
                        .WithMany()
                        .HasForeignKey("MaPhienBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarProject.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PhienBan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CarProject.Models.HoaDonMuaXe", b =>
                {
                    b.HasOne("CarProject.Models.DonDatCoc", "DonDatCoc")
                        .WithMany()
                        .HasForeignKey("MaDonCoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatCoc");
                });

            modelBuilder.Entity("CarProject.Models.LichHenLaiThu", b =>
                {
                    b.HasOne("CarProject.Models.ChiNhanhShowroom", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarProject.Models.DongXe", "DongXe")
                        .WithMany()
                        .HasForeignKey("MaDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarProject.Models.TaiKhoan", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("DongXe");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("CarProject.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("CarProject.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CarProject.Models.PhienBanXe", b =>
                {
                    b.HasOne("CarProject.Models.DongXe", "DongXe")
                        .WithMany()
                        .HasForeignKey("MaDong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DongXe");
                });

            modelBuilder.Entity("CarProject.Models.QuangCaoBanner", b =>
                {
                    b.HasOne("CarProject.Models.TaiKhoan", "QuanLyCapNhat")
                        .WithMany()
                        .HasForeignKey("MaQuanLyCapNhat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("QuanLyCapNhat");
                });

            modelBuilder.Entity("CarProject.Models.ThongKeTongHop_Boss", b =>
                {
                    b.HasOne("CarProject.Models.ChiNhanhShowroom", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaChiNhanh")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarProject.Models.DongXe", "DongXeBanChay")
                        .WithMany()
                        .HasForeignKey("MaDongXeBanChayNhat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("DongXeBanChay");
                });
#pragma warning restore 612, 618
        }
    }
}
